service: fe-digest-canva

frameworkVersion: "3"

plugins:
  - serverless-deployment-bucket
  - serverless-s3-sync

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${env:STAGE}
  region: ${env:REGION}
  profile: ${env:AWS_PROFILE}
  memorySize: 128
  timeout: 10
  logRetentionInDays: 7
  deploymentBucket:
    name: net.${self:service}.${self:provider.region}.${aws:accountId}.deploys
  versionFunctions: false
  environment:
    STAGE: ${self:provider.stage}
    REGION: ${self:provider.region}
    AWS_ACCOUNT_ID: ${aws:accountId}
  stackTags:
    SERVICE: "${self:service}"
    REGION: "${self:provider.region}"

custom:
  frontendBucketName: ${self:service}.${env:DOMAIN}
  deploymentBucket:
    blockPublicAccess: true
  s3Sync:
    - bucketName: ${self:custom.frontendBucketName}
      localDir: ./build/static/js
      bucketPrefix: js/
      deleteRemoved: true
      acl: public-read
    - bucketName: ${self:custom.frontendBucketName}
      bucketPrefix: assets/
      localDir: ./build/assets
      deleteRemoved: true
      acl: public-read

resources:
  Resources:
    digestCanvaFrontendFiles:
      Type: AWS::S3::Bucket
      DeletionPolicy: Retain
      UpdateReplacePolicy: Retain
      Properties:
        BucketName: ${self:custom.frontendBucketName}
        OwnershipControls:
          Rules:
            - ObjectOwnership: ObjectWriter
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: false
          RestrictPublicBuckets: false
